language: node_js
node_js:
  - '8'
install:
  - 'npm i -g npm@next'
  - 'npm install'
script:
  - 'npm run clean-build'
deploy:
  provider: 'script'
  skip_cleanup: true
  script: git clone https://github.com/paramorph/paramorph-deploy && ./paramorph-deploy/deploy.sh master https://github.com/paramorph/paramorph.github.io
  on:
    branch: 'master'

